
import { DictionaryEntry } from './types';

export const BUSINESS_CODE_DICTIONARY: Record<string, DictionaryEntry> = {
  "01": { normalizedDescription: "Refer to Card Issuer", typicalCause: "Issuer requires manual verification or additional checks before approving the transaction." },
  "02": { normalizedDescription: "Refer to Card Issuer – Special Condition", typicalCause: "Issuer has flagged the transaction for special handling due to risk, account status, or compliance rules." },
  "03": { normalizedDescription: "Invalid Merchant", typicalCause: "Merchant ID is not recognized, inactive, or not permitted by the issuer or network." },
  "04": { normalizedDescription: "Pick Up Card", typicalCause: "Card has been flagged as compromised; issuer requests card retention at terminal." },
  "05": { normalizedDescription: "Do Not Honour", typicalCause: "Generic issuer decline; may be due to insufficient funds, suspected fraud triggers, card restrictions, incorrect card details, or issuer risk rules." },
  "06": { normalizedDescription: "Check Value Error", typicalCause: "Transaction amount or value field is invalid or does not meet issuer validation rules." },
  "08": { normalizedDescription: "Signature Required", typicalCause: "Issuer requires signature verification; terminal may not support signature capture." },
  "12": { normalizedDescription: "Invalid Transaction", typicalCause: "Transaction type is not valid for the card, account, or terminal configuration." },
  "13": { normalizedDescription: "Invalid Amount", typicalCause: "Transaction amount is incorrect, zero, negative, or exceeds allowable limits." },
  "14": { normalizedDescription: "Invalid Card Number", typicalCause: "Card number is incorrect, does not exist, or failed validation checks." },
  "19": { normalizedDescription: "Re-enter Transaction", typicalCause: "Temporary issue detected; issuer requests transaction retry." },
  "20": { normalizedDescription: "Amount Mismatch", typicalCause: "Transaction amount differs from expected or previously authorized value." },
  "22": { normalizedDescription: "No Cheque Account", typicalCause: "Cardholder does not have a cheque/current account linked to the card." },
  "23": { normalizedDescription: "No Saving Account", typicalCause: "Cardholder does not have a savings account linked to the card." },
  "24": { normalizedDescription: "No Credit Account", typicalCause: "Cardholder does not have a credit account linked to the card." },
  "25": { normalizedDescription: "Unable to Locate Record on File", typicalCause: "Issuer cannot find the card or account record in its system." },
  "34": { normalizedDescription: "Fraud Card", typicalCause: "Card flagged as fraudulent by issuer due to confirmed or suspected misuse." },
  "39": { normalizedDescription: "No Credit Account", typicalCause: "Credit account not available or not permitted for this transaction." },
  "40": { normalizedDescription: "Function Not Supported by Issuer", typicalCause: "Issuer does not support the requested transaction type or feature." },
  "41": { normalizedDescription: "Lost Card", typicalCause: "Card reported lost; issuer blocks all transactions." },
  "43": { normalizedDescription: "Stolen Card", typicalCause: "Card reported stolen; issuer blocks all transactions." },
  "44": { normalizedDescription: "Block / Terminate / Close / Destroy Card", typicalCause: "Card permanently blocked due to security or compliance reasons." },
  "45": { normalizedDescription: "New Unactivated Card", typicalCause: "Card has not yet been activated by the cardholder." },
  "46": { normalizedDescription: "Closed Card Account", typicalCause: "Card account has been closed by issuer or cardholder." },
  "51": { normalizedDescription: "Insufficient Funds", typicalCause: "Cardholder’s available balance is insufficient to cover the transaction amount." },
  "52": { normalizedDescription: "No Current Account", typicalCause: "Current account not available or not linked to the card." },
  "53": { normalizedDescription: "No Saving Account", typicalCause: "Savings account not available or inactive." },
  "54": { normalizedDescription: "Expired Card", typicalCause: "Card has expired and is no longer valid for transactions." },
  "55": { normalizedDescription: "Incorrect PIN", typicalCause: "Cardholder entered an incorrect PIN." },
  "56": { normalizedDescription: "No Card Record", typicalCause: "Issuer cannot locate the card record in its system." },
  "57": { normalizedDescription: "Transaction Not Permitted to Card", typicalCause: "Issuer has disabled this transaction type for the card (e.g., POS, ATM, international usage)." },
  "58": { normalizedDescription: "Transaction Not Permitted to Terminal", typicalCause: "Issuer does not allow transactions from this terminal type or configuration." },
  "59": { normalizedDescription: "Suspected Fraud", typicalCause: "Transaction flagged by issuer’s fraud monitoring system due to unusual behaviour, location mismatch, or risk scoring." },
  "5C": { normalizedDescription: "Not Supported by Issuer", typicalCause: "Issuer does not support this transaction or feature for the card product." },
  "61": { normalizedDescription: "Exceed Amount Limit", typicalCause: "Transaction amount exceeds cardholder’s daily or transaction limit set by issuer." },
  "62": { normalizedDescription: "Restricted Card", typicalCause: "Card usage restricted due to issuer rules, MCC blocks, geographic limits, or temporary security controls." },
  "65": { normalizedDescription: "Exceed Count Limit", typicalCause: "Number of allowed transactions exceeded issuer-defined daily or periodic limits." },
  "72": { normalizedDescription: "Unactivated Account", typicalCause: "Underlying account linked to the card is not activated." },
  "75": { normalizedDescription: "PIN Try Exceeded", typicalCause: "Maximum number of PIN attempts exceeded; card temporarily blocked." },
  "78": { normalizedDescription: "Unactivated / Block Card", typicalCause: "Card is inactive or blocked due to security, compliance, or customer action." },
  "79": { normalizedDescription: "Declined", typicalCause: "Issuer declined the transaction without providing a specific reason." },
  "82": { normalizedDescription: "Negative Online CAM/CVV Results", typicalCause: "CVV/CVC or card authentication verification failed during authorization." },
  "83": { normalizedDescription: "Issuer Blocked Due to Security Reason", typicalCause: "Issuer blocked transaction due to heightened security or risk concerns." },
  "85": { normalizedDescription: "Not Declined", typicalCause: "Informational response; transaction outcome handled outside standard decline flow." },
  "86": { normalizedDescription: "Cannot Verify PIN", typicalCause: "PIN verification could not be completed due to system or data issues." },
  "87": { normalizedDescription: "PIN Required", typicalCause: "Issuer requires PIN entry, but PIN was not provided." },
  "9G": { normalizedDescription: "Blocked by Cardholder", typicalCause: "Cardholder manually blocked the card via banking app or customer service." },
  // Former Technical Codes now Business per requirements
  "63": { normalizedDescription: "MAC Verification Error", typicalCause: "Message authentication code validation failed due to key mismatch or data corruption." },
  "68": { normalizedDescription: "Issuer Timeout", typicalCause: "Issuer did not respond within the expected time window." },
  "77": { normalizedDescription: "Reconcile Error", typicalCause: "Transaction reconciliation mismatch between terminal and host system." },
  "80": { normalizedDescription: "Batch Number Not Found", typicalCause: "Settlement batch reference not found at host or acquirer system." },
  "84": { normalizedDescription: "Validate ARQC Error", typicalCause: "EMV cryptogram validation failed during transaction authentication." },
  "88": { normalizedDescription: "Crypto Failed", typicalCause: "Cryptographic validation failure during EMV processing." },
  "89": { normalizedDescription: "Bad Terminal ID", typicalCause: "Terminal ID is invalid, unregistered, or misconfigured." },
  "92": { normalizedDescription: "Routing Error", typicalCause: "Transaction could not be routed correctly to issuer or network." },
  "94": { normalizedDescription: "Duplicate Transaction", typicalCause: "Transaction already processed; duplicate detected." },
  "95": { normalizedDescription: "Reconcile Error", typicalCause: "Settlement or reconciliation error detected post-authorization." },
  "97": { normalizedDescription: "Account Currency Error", typicalCause: "Currency mismatch between account and transaction." },
  "98": { normalizedDescription: "Issuer Timeout (CUP)", typicalCause: "Issuer did not respond within timeout window (CUP-specific)." },
  "99": { normalizedDescription: "PIN Block Error", typicalCause: "PIN block formatting or encryption error." },
  "A4": { normalizedDescription: "Acquirer Timeout", typicalCause: "Acquirer system timeout during transaction processing." },
  "A5": { normalizedDescription: "Acquirer Link Down", typicalCause: "Connectivity issue between terminal and acquirer host." },
  "C0": { normalizedDescription: "Database Connection Error", typicalCause: "Backend database connectivity issue." },
  "C2": { normalizedDescription: "Invalid Chip Card Data", typicalCause: "EMV chip data invalid or unreadable." }
};

export const TECHNICAL_CODE_DICTIONARY: Record<string, DictionaryEntry> = {
  "30": { normalizedDescription: "Format Error", typicalCause: "Transaction message did not conform to ISO 8583 standards; often due to incorrect field mapping or terminal configuration issues." },
  "91": { normalizedDescription: "Issuer or Switch Is Inoperative", typicalCause: "Issuer or intermediary switch temporarily unavailable." },
  "96": { normalizedDescription: "System Malfunction", typicalCause: "General technical failure due to host issues, network interruption, or processing error." }
};

export const REASON_NORMALIZATION: Record<string, DictionaryEntry> = {
  "do not honour": { normalizedDescription: "Do Not Honour", typicalCause: "Generic issuer decline; may occur due to insufficient funds, suspected fraud, or incorrect card details." },
  "card violation cannot complete": { normalizedDescription: "Card Violation Cannot Complete", typicalCause: "Issuer blocked the transaction due to rule or policy violations." },
  "suspected fraud": { normalizedDescription: "Suspected Fraud", typicalCause: "Transaction flagged by issuer’s fraud monitoring system." },
  "insufficient funds": { normalizedDescription: "Insufficient Funds", typicalCause: "Cardholder’s account balance is insufficient for the transaction amount." },
  "restricted card": { normalizedDescription: "Restricted Card", typicalCause: "Card restricted for certain uses, regions, or merchant types." },
  "incorrect pin": { normalizedDescription: "Incorrect PIN", typicalCause: "Cardholder entered the wrong PIN at the POS terminal." },
  "exceed amount limit": { normalizedDescription: "Exceed Amount Limit", typicalCause: "Transaction amount exceeded issuer- or cardholder-set limits." },
  "negative online cam/cvv results": { normalizedDescription: "Negative Online CAM/CVV Results", typicalCause: "Failed CVV/CVC or CAM validation during authorization." },
  "blocked by cardholder": { normalizedDescription: "Blocked by Cardholder", typicalCause: "Cardholder manually blocked or froze the card." },
  "invalid transaction": { normalizedDescription: "Invalid Transaction", typicalCause: "Transaction type not valid for the card, account, or POS terminal." }
};
